// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'API KEY',
      appId: "APP ID",
      messagingSenderId: "SENSDER ID",
      projectId: "Android PROJECT ID",
      databaseURL: "DATABASE URL");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API KEY',
    appId: "APP ID",
    messagingSenderId: "SENSDER ID",
    projectId: 'IOS PROJECT ID',
    databaseURL: "DATABASE URL",
  );
}
