name: components
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0-364.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
