name: firebase_integration
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0-364.0.dev <3.0.0'

dependencies:
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_database: ^10.0.4
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
